# i18n Ally 配置文件
# 用于支持项目的多语言文件结构

# 语言标签系统
languageTagSystem: standard

# 扫描忽略的文件
usage:
  scanningIgnore:
    - "node_modules/**"
    - "dist/**"
    - "out/**"
    - "build/**"
    - "**/*.d.ts"

# 翻译文件路径模式
pathMatcher: "frontend/src/i18n/locales/{locale}/{namespace}.json"

# 命名空间配置
namespace: true
defaultNamespace: "app"
namespaceSeparator: ":"
keySeparator: "."

# 支持的语言列表
localesPaths:
  - "frontend/src/i18n/locales"

# 源语言（用于提取未翻译的键）
sourceLanguage: "zh-CN"

# 显示语言
displayLanguage: "zh-CN"

# 编辑器配置
editor:
  # 显示内联翻译
  display: true
  # 显示语言标签
  showLanguageTag: true
  # 显示命名空间
  showNamespace: true

# 翻译器配置（可选）
translators:
  - "google"
  - "bing"

