export { default as Search } from './Search/search'
export { default as InfoCard } from './InfoCard/InfoCard'
export { default as Setting } from './Setting/Setting'
export { default as Dialog } from './Dialog/Dialog'
export { default as Contact } from './Contact/Contact'