import { FlagComponent } from './FlagIcons';
import * as FlagIcons from './FlagIcons';

// 國旗數據數組（國家名稱、代碼、組件）
const flagsData: [string, string, React.FC<FlagIcons.FlagIconProps>][] = [
    ['Aaland Islands', 'ax', FlagIcons.AalandIslandsFlag],
    ['Afghanistan', 'af', FlagIcons.AfghanistanFlag],
    ['Albania', 'al', FlagIcons.AlbaniaFlag],
    ['Algeria', 'dz', FlagIcons.AlgeriaFlag],
    ['American Samoa', 'as', FlagIcons.AmericanSamoaFlag],
    ['Andorra', 'ad', FlagIcons.AndorraFlag],
    ['Angola', 'ao', FlagIcons.AngolaFlag],
    ['Anguilla', 'ai', FlagIcons.AnguillaFlag],
    ['Antarctica', 'aq', FlagIcons.AntarcticaFlag],
    ['Antigua and Barbuda', 'ag', FlagIcons.AntiguaAndBarbudaFlag],
    ['Argentina', 'ar', FlagIcons.ArgentinaFlag],
    ['Armenia', 'am', FlagIcons.ArmeniaFlag],
    ['Aruba', 'aw', FlagIcons.ArubaFlag],
    ['Australia', 'au', FlagIcons.AustraliaFlag],
    ['Austria', 'at', FlagIcons.AustriaFlag],
    ['Azerbaijan', 'az', FlagIcons.AzerbaijanFlag],
    ['Bahamas', 'bs', FlagIcons.BahamasFlag],
    ['Bahrain', 'bh', FlagIcons.BahrainFlag],
    ['Bangladesh', 'bd', FlagIcons.BangladeshFlag],
    ['Barbados', 'bb', FlagIcons.BarbadosFlag],
    ['Belarus', 'by', FlagIcons.BelarusFlag],
    ['Belgium', 'be', FlagIcons.BelgiumFlag],
    ['Belize', 'bz', FlagIcons.BelizeFlag],
    ['Benin', 'bj', FlagIcons.BeninFlag],
    ['Bermuda', 'bm', FlagIcons.BermudaFlag],
    ['Bhutan', 'bt', FlagIcons.BhutanFlag],
    ['Bolivia', 'bo', FlagIcons.BoliviaFlag],
    ['Bosnia and Herzegovina', 'ba', FlagIcons.BosniaAndHerzegovinaFlag],
    ['Botswana', 'bw', FlagIcons.BotswanaFlag],
    ['Brazil', 'br', FlagIcons.BrazilFlag],
    ['British Indian Ocean Territory', 'io', FlagIcons.BritishIndianOceanTerritoryFlag],
    ['Brunei', 'bn', FlagIcons.BruneiFlag],
    ['Bulgaria', 'bg', FlagIcons.BulgariaFlag],
    ['Burkina Faso', 'bf', FlagIcons.BurkinaFasoFlag],
    ['Burundi', 'bi', FlagIcons.BurundiFlag],
    ['Cambodia', 'kh', FlagIcons.CambodiaFlag],
    ['Cameroon', 'cm', FlagIcons.CameroonFlag],
    ['Canada', 'ca', FlagIcons.CanadaFlag],
    ['Cape Verde', 'cv', FlagIcons.CapeVerdeFlag],
    ['Cayman Islands', 'ky', FlagIcons.CaymanIslandsFlag],
    ['Central African Republic', 'cf', FlagIcons.CentralAfricanRepublicFlag],
    ['Chad', 'td', FlagIcons.ChadFlag],
    ['Chile', 'cl', FlagIcons.ChileFlag],
    ['China', 'cn', FlagIcons.ChinaFlag],
    ['Christmas Island', 'cx', FlagIcons.ChristmasIslandFlag],
    ['Cocos Islands', 'cc', FlagIcons.CocosIslandsFlag],
    ['Colombia', 'co', FlagIcons.ColombiaFlag],
    ['Comoros', 'km', FlagIcons.ComorosFlag],
    ['Congo', 'cg', FlagIcons.CongoFlag],
    ['Congo (Democratic Republic)', 'cd', FlagIcons.CongoDemocraticRepublicFlag],
    ['Cook Islands', 'ck', FlagIcons.CookIslandsFlag],
    ['Costa Rica', 'cr', FlagIcons.CostaRicaFlag],
    ['Croatia', 'hr', FlagIcons.CroatiaFlag],
    ['Cuba', 'cu', FlagIcons.CubaFlag],
    ['Curacao', 'cw', FlagIcons.CuracaoFlag],
    ['Cyprus', 'cy', FlagIcons.CyprusFlag],
    ['Czech Republic', 'cz', FlagIcons.CzechRepublicFlag],
    ['Denmark', 'dk', FlagIcons.DenmarkFlag],
    ['Djibouti', 'dj', FlagIcons.DjiboutiFlag],
    ['Dominica', 'dm', FlagIcons.DominicaFlag],
    ['Dominican Republic', 'do', FlagIcons.DominicanRepublicFlag],
    ['Ecuador', 'ec', FlagIcons.EcuadorFlag],
    ['Egypt', 'eg', FlagIcons.EgyptFlag],
    ['El Salvador', 'sv', FlagIcons.ElSalvadorFlag],
    ['England', 'gb-eng', FlagIcons.EnglandFlag],
    ['Equatorial Guinea', 'gq', FlagIcons.EquatorialGuineaFlag],
    ['Eritrea', 'er', FlagIcons.EritreaFlag],
    ['Estonia', 'ee', FlagIcons.EstoniaFlag],
    ['Ethiopia', 'et', FlagIcons.EthiopiaFlag],
    ['European Union', 'eu', FlagIcons.EuropeanUnionFlag],
    ['Falkland Islands', 'fk', FlagIcons.FalklandIslandsFlag],
    ['Faroe Islands', 'fo', FlagIcons.FaroeIslandsFlag],
    ['Fiji', 'fj', FlagIcons.FijiFlag],
    ['Finland', 'fi', FlagIcons.FinlandFlag],
    ['France', 'fr', FlagIcons.FranceFlag],
    ['French Guiana', 'gf', FlagIcons.FrenchGuianaFlag],
    ['French Polynesia', 'pf', FlagIcons.FrenchPolynesiaFlag],
    ['French Southern Territories', 'tf', FlagIcons.FrenchSouthernTerritoriesFlag],
    ['Gabon', 'ga', FlagIcons.GabonFlag],
    ['Gambia', 'gm', FlagIcons.GambiaFlag],
    ['Georgia', 'ge', FlagIcons.GeorgiaFlag],
    ['Germany', 'de', FlagIcons.GermanyFlag],
    ['Ghana', 'gh', FlagIcons.GhanaFlag],
    ['Gibraltar', 'gi', FlagIcons.GibraltarFlag],
    ['Greece', 'gr', FlagIcons.GreeceFlag],
    ['Greenland', 'gl', FlagIcons.GreenlandFlag],
    ['Grenada', 'gd', FlagIcons.GrenadaFlag],
    ['Guadeloupe', 'gp', FlagIcons.GuadeloupeFlag],
    ['Guam', 'gu', FlagIcons.GuamFlag],
    ['Guatemala', 'gt', FlagIcons.GuatemalaFlag],
    ['Guernsey', 'gg', FlagIcons.GuernseyFlag],
    ['Guinea', 'gn', FlagIcons.GuineaFlag],
    ['Guinea-Bissau', 'gw', FlagIcons.GuineaBissauFlag],
    ['Guyana', 'gy', FlagIcons.GuyanaFlag],
    ['Haiti', 'ht', FlagIcons.HaitiFlag],
    ['Honduras', 'hn', FlagIcons.HondurasFlag],
    ['Hong Kong', 'hk', FlagIcons.HongKongFlag],
    ['Hungary', 'hu', FlagIcons.HungaryFlag],
    ['Iceland', 'is', FlagIcons.IcelandFlag],
    ['India', 'in', FlagIcons.IndiaFlag],
    ['Indonesia', 'id', FlagIcons.IndonesiaFlag],
    ['Iran', 'ir', FlagIcons.IranFlag],
    ['Iraq', 'iq', FlagIcons.IraqFlag],
    ['Ireland', 'ie', FlagIcons.IrelandFlag],
    ['Isle of Man', 'im', FlagIcons.IsleOfManFlag],
    ['Israel', 'il', FlagIcons.IsraelFlag],
    ['Italy', 'it', FlagIcons.ItalyFlag],
    ['Ivory Coast', 'ci', FlagIcons.IvoryCoastFlag],
    ['Jamaica', 'jm', FlagIcons.JamaicaFlag],
    ['Japan', 'jp', FlagIcons.JapanFlag],
    ['Jersey', 'je', FlagIcons.JerseyFlag],
    ['Jordan', 'jo', FlagIcons.JordanFlag],
    ['Kazakhstan', 'kz', FlagIcons.KazakhstanFlag],
    ['Kenya', 'ke', FlagIcons.KenyaFlag],
    ['Kiribati', 'ki', FlagIcons.KiribatiFlag],
    ['Kosovo', 'xk', FlagIcons.KosovoFlag],
    ['Kuwait', 'kw', FlagIcons.KuwaitFlag],
    ['Kyrgyzstan', 'kg', FlagIcons.KyrgyzstanFlag],
    ['Laos', 'la', FlagIcons.LaosFlag],
    ['Latvia', 'lv', FlagIcons.LatviaFlag],
    ['Lebanon', 'lb', FlagIcons.LebanonFlag],
    ['Lesotho', 'ls', FlagIcons.LesothoFlag],
    ['Liberia', 'lr', FlagIcons.LiberiaFlag],
    ['Libya', 'ly', FlagIcons.LibyaFlag],
    ['Liechtenstein', 'li', FlagIcons.LiechtensteinFlag],
    ['Lithuania', 'lt', FlagIcons.LithuaniaFlag],
    ['Luxembourg', 'lu', FlagIcons.LuxembourgFlag],
    ['Macau', 'mo', FlagIcons.MacauFlag],
    ['Macedonia', 'mk', FlagIcons.MacedoniaFlag],
    ['Madagascar', 'mg', FlagIcons.MadagascarFlag],
    ['Malawi', 'mw', FlagIcons.MalawiFlag],
    ['Malaysia', 'my', FlagIcons.MalaysiaFlag],
    ['Maldives', 'mv', FlagIcons.MaldivesFlag],
    ['Mali', 'ml', FlagIcons.MaliFlag],
    ['Malta', 'mt', FlagIcons.MaltaFlag],
    ['Marshall Islands', 'mh', FlagIcons.MarshallIslandsFlag],
    ['Martinique', 'mq', FlagIcons.MartiniqueFlag],
    ['Mauritania', 'mr', FlagIcons.MauritaniaFlag],
    ['Mauritius', 'mu', FlagIcons.MauritiusFlag],
    ['Mayotte', 'yt', FlagIcons.MayotteFlag],
    ['Mexico', 'mx', FlagIcons.MexicoFlag],
    ['Micronesia', 'fm', FlagIcons.MicronesiaFlag],
    ['Moldova', 'md', FlagIcons.MoldovaFlag],
    ['Monaco', 'mc', FlagIcons.MonacoFlag],
    ['Mongolia', 'mn', FlagIcons.MongoliaFlag],
    ['Montenegro', 'me', FlagIcons.MontenegroFlag],
    ['Montserrat', 'ms', FlagIcons.MontserratFlag],
    ['Morocco', 'ma', FlagIcons.MoroccoFlag],
    ['Mozambique', 'mz', FlagIcons.MozambiqueFlag],
    ['Myanmar', 'mm', FlagIcons.MyanmarFlag],
    ['Namibia', 'na', FlagIcons.NamibiaFlag],
    ['Nauru', 'nr', FlagIcons.NauruFlag],
    ['Nepal', 'np', FlagIcons.NepalFlag],
    ['Netherlands', 'nl', FlagIcons.NetherlandsFlag],
    ['New Caledonia', 'nc', FlagIcons.NewCaledoniaFlag],
    ['New Zealand', 'nz', FlagIcons.NewZealandFlag],
    ['Nicaragua', 'ni', FlagIcons.NicaraguaFlag],
    ['Niger', 'ne', FlagIcons.NigerFlag],
    ['Nigeria', 'ng', FlagIcons.NigeriaFlag],
    ['Niue', 'nu', FlagIcons.NiueFlag],
    ['Norfolk Island', 'nf', FlagIcons.NorfolkIslandFlag],
    ['North Korea', 'kp', FlagIcons.NorthKoreaFlag],
    ['Northern Ireland', 'gb-nir', FlagIcons.NorthernIrelandFlag],
    ['Northern Mariana Islands', 'mp', FlagIcons.NorthernMarianaIslandsFlag],
    ['Norway', 'no', FlagIcons.NorwayFlag],
    ['Oman', 'om', FlagIcons.OmanFlag],
    ['Pakistan', 'pk', FlagIcons.PakistanFlag],
    ['Palau', 'pw', FlagIcons.PalauFlag],
    ['Palestine', 'ps', FlagIcons.PalestineFlag],
    ['Panama', 'pa', FlagIcons.PanamaFlag],
    ['Papua New Guinea', 'pg', FlagIcons.PapuaNewGuineaFlag],
    ['Paraguay', 'py', FlagIcons.ParaguayFlag],
    ['Peru', 'pe', FlagIcons.PeruFlag],
    ['Philippines', 'ph', FlagIcons.PhilippinesFlag],
    ['Pitcairn Islands', 'pn', FlagIcons.PitcairnIslandsFlag],
    ['Poland', 'pl', FlagIcons.PolandFlag],
    ['Portugal', 'pt', FlagIcons.PortugalFlag],
    ['Puerto Rico', 'pr', FlagIcons.PuertoRicoFlag],
    ['Qatar', 'qa', FlagIcons.QatarFlag],
    ['Reunion', 're', FlagIcons.ReunionFlag],
    ['Romania', 'ro', FlagIcons.RomaniaFlag],
    ['Russia', 'ru', FlagIcons.RussiaFlag],
    ['Rwanda', 'rw', FlagIcons.RwandaFlag],
    ['Saint Barthelemy', 'bl', FlagIcons.SaintBarthelemyFlag],
    ['Saint Helena', 'sh', FlagIcons.SaintHelenaFlag],
    ['Saint Kitts and Nevis', 'kn', FlagIcons.SaintKittsAndNevisFlag],
    ['Saint Lucia', 'lc', FlagIcons.SaintLuciaFlag],
    ['Saint Martin', 'mf', FlagIcons.SaintMartinFlag],
    ['Saint Pierre and Miquelon', 'pm', FlagIcons.SaintPierreAndMiquelonFlag],
    ['Saint Vincent and the Grenadines', 'vc', FlagIcons.SaintVincentAndTheGrenadinesFlag],
    ['Samoa', 'ws', FlagIcons.SamoaFlag],
    ['San Marino', 'sm', FlagIcons.SanMarinoFlag],
    ['Sao Tome and Principe', 'st', FlagIcons.SaoTomeAndPrincipeFlag],
    ['Saudi Arabia', 'sa', FlagIcons.SaudiArabiaFlag],
    ['Scotland', 'gb-sct', FlagIcons.ScotlandFlag],
    ['Senegal', 'sn', FlagIcons.SenegalFlag],
    ['Serbia', 'rs', FlagIcons.SerbiaFlag],
    ['Seychelles', 'sc', FlagIcons.SeychellesFlag],
    ['Sierra Leone', 'sl', FlagIcons.SierraLeoneFlag],
    ['Singapore', 'sg', FlagIcons.SingaporeFlag],
    ['Sint Maarten', 'sx', FlagIcons.SintMaartenFlag],
    ['Slovakia', 'sk', FlagIcons.SlovakiaFlag],
    ['Slovenia', 'si', FlagIcons.SloveniaFlag],
    ['Solomon Islands', 'sb', FlagIcons.SolomonIslandsFlag],
    ['Somalia', 'so', FlagIcons.SomaliaFlag],
    ['South Africa', 'za', FlagIcons.SouthAfricaFlag],
    ['South Korea', 'kr', FlagIcons.SouthKoreaFlag],
    ['South Sudan', 'ss', FlagIcons.SouthSudanFlag],
    ['Spain', 'es', FlagIcons.SpainFlag],
    ['Sri Lanka', 'lk', FlagIcons.SriLankaFlag],
    ['Sudan', 'sd', FlagIcons.SudanFlag],
    ['Suriname', 'sr', FlagIcons.SurinameFlag],
    ['Svalbard and Jan Mayen', 'sj', FlagIcons.SvalbardAndJanMayenFlag],
    ['Swaziland', 'sz', FlagIcons.SwazilandFlag],
    ['Sweden', 'se', FlagIcons.SwedenFlag],
    ['Switzerland', 'ch', FlagIcons.SwitzerlandFlag],
    ['Syria', 'sy', FlagIcons.SyriaFlag],
    ['Taiwan', 'tw', FlagIcons.TaiwanFlag],
    ['Tajikistan', 'tj', FlagIcons.TajikistanFlag],
    ['Tanzania', 'tz', FlagIcons.TanzaniaFlag],
    ['Thailand', 'th', FlagIcons.ThailandFlag],
    ['Timor-Leste', 'tl', FlagIcons.TimorLesteFlag],
    ['Togo', 'tg', FlagIcons.TogoFlag],
    ['Tokelau', 'tk', FlagIcons.TokelauFlag],
    ['Tonga', 'to', FlagIcons.TongaFlag],
    ['Trinidad and Tobago', 'tt', FlagIcons.TrinidadAndTobagoFlag],
    ['Tunisia', 'tn', FlagIcons.TunisiaFlag],
    ['Turkey', 'tr', FlagIcons.TurkeyFlag],
    ['Turkmenistan', 'tm', FlagIcons.TurkmenistanFlag],
    ['Turks and Caicos Islands', 'tc', FlagIcons.TurksAndCaicosIslandsFlag],
    ['Tuvalu', 'tv', FlagIcons.TuvaluFlag],
    ['Uganda', 'ug', FlagIcons.UgandaFlag],
    ['Ukraine', 'ua', FlagIcons.UkraineFlag],
    ['United Arab Emirates', 'ae', FlagIcons.UnitedArabEmiratesFlag],
    ['United Kingdom', 'gb', FlagIcons.UnitedKingdomFlag],
    ['United States', 'us', FlagIcons.UnitedStatesFlag],
    ['Uruguay', 'uy', FlagIcons.UruguayFlag],
    ['Uzbekistan', 'uz', FlagIcons.UzbekistanFlag],
    ['Vanuatu', 'vu', FlagIcons.VanuatuFlag],
    ['Vatican City', 'va', FlagIcons.VaticanCityFlag],
    ['Venezuela', 've', FlagIcons.VenezuelaFlag],
    ['Vietnam', 'vn', FlagIcons.VietnamFlag],
    ['Virgin Islands (British)', 'vg', FlagIcons.VirginIslandsBritishFlag],
    ['Virgin Islands (US)', 'vi', FlagIcons.VirginIslandsUSFlag],
    ['Wales', 'gb-wls', FlagIcons.WalesFlag],
    ['Wallis and Futuna', 'wf', FlagIcons.WallisAndFutunaFlag],
    ['Western Sahara', 'eh', FlagIcons.WesternSaharaFlag],
    ['Yemen', 'ye', FlagIcons.YemenFlag],
    ['Zambia', 'zm', FlagIcons.ZambiaFlag],
    ['Zimbabwe', 'zw', FlagIcons.ZimbabweFlag],
];

/**
 * @description 使用 map 函數生成最終的 allFlags 數組
 */
export const allFlags: FlagComponent[] = flagsData.map(([name, code, component]) => ({
    name,
    code,
    component,
}));

/**
 * @description 按國家名稱查找國旗組件的輔助函數
 * @param name 國家名稱
 * @returns 國旗組件或 undefined
 */
export const getFlagByName = (name: string): FlagComponent | undefined => {
    return allFlags.find(flag => flag.name.toLowerCase() === name.toLowerCase());
};

/**
 * @description 按國家代碼查找國旗組件的輔助函數
 * @param code 國家代碼
 * @returns 國旗組件或 undefined
 */
export const getFlagByCode = (code: string): FlagComponent | undefined => {
    return allFlags.find(flag => flag.code.toLowerCase() === code.toLowerCase());
};

